version: '3.4'

services:
  tweeter_opentechiz:
    image: nguyenviethoa/tweeter-opentechiz:build-latest
    deploy:
      replicas: 1
    working_dir: /app  
    ports:
      - 8099:4000
    command: "npm start"  
    
