version: '3.4'

services:
  tweeter_opentechiz:
    image: nguyenviethoa/tweeter-opentechiz:build-latest
    deploy:
      replicas: 1
      restart_policy: 
        condition: any
    ports:
      - 8099:4000
